Add mksource function

diff --git a/sources/functions b/sources/functions
--- a/sources/functions
+++ b/sources/functions
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 # List directory contents after cd
+# This is a special hook function called by zsh
 function chpwd() {
   ls
 }
@@ -14,5 +15,16 @@ function mkscript() {
 
   echo "#!/bin/sh" > $1
   chmod 777 $1
+  return 0
+}
+
+# Create source file with hash-bang line
+function mksource() {
+  if [ -e $1 ]; then
+    echo "ERROR: $1 already exists" 1>&2
+    return 1
+  fi
+
+  echo "#!/bin/sh" > $1
   return 0
 }
